AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.5
  Exclude:
    - '*/vendor/**/*'
    - '*/bin/**/*'
    - '*/tmp/**/*'
    - 'tmp/**/*'
    - '*/helpers/**/*'

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false   

Layout/LineLength:
  Max: 80

Layout/RescueEnsureAlignment:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: false  

Lint/DeprecatedOpenSSLConstant:
  Enabled: false

Lint/MixedRegexpCaptureTypes:
  Enabled: false

Lint/RaiseException:
  Enabled: false

Lint/StructNewOverride:
  Enabled: false

Metrics/ClassLength:
  Max: 350

Metrics/ModuleLength:
  Max: 350

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/AbcSize:
  Max: 35

Metrics/MethodLength:
  Max: 35

Metrics/BlockLength:
  Max: 35
  Exclude:
    - '*/Rakefile'
    - '*/spec/**/*'
    - '*/dependabot-*.gemspec'

Metrics/ParameterLists:
  CountKeywordArgs: false

Naming/FileName:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SignalException:
  EnforcedStyle: only_raise

Style/Documentation:
  Enabled: false

Style/HashEachMethods:
  Enabled: false  

Style/HashTransformKeys:
  Enabled: false
  
Style/HashTransformValues:
  Enabled: false
  
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': ()
    '%I': ()
    '%w': ()
    '%W': ()

Style/ExponentialNotation:
  Enabled: false

Style/RedundantRegexpCharacterClass:
  Enabled: false

Style/RedundantRegexpEscape:
  Enabled: false

Style/SlicingWithRange:
  Enabled: false